### ISSUE TITLE
Dockerfile for warmup

### ISSUE THREAD

**Issue by abdilahrf** [w181496/My-CTF-Challenges#1]
Hi w181496, 

thanks for this writeup and source code, the challenges was really pain and combination of very clever bugs.

i want to ask if you have the dockerfile for the Warmup challenges for me to deploy on my local environment, Much thanks!

**Comment by w181496** [comment]
Sorry, this challenge was built on AWS Windows instance, so there is no dockerfile.

But if you want to build a similar local environment, you can just install XAMPP on a Windows machine and set the `secure_file_priv=` in your mysqld config.
